# Generated by Django 3.1.7 on 2021-08-30 03:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloTelefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.CharField(choices=[('Samsung', 'Samsung'), ('Apple', 'Apple')], default='Apple', max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Modelos de teléfono',
                'ordering': ['marca', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Monedero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('dinero', models.FloatField(blank=True, default=0, null=True)),
                ('fecha_actualizacion', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Monederos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidad', models.CharField(choices=[('Open box', 'Open box'), ('Sellado', 'Sellado')], default='Open box', max_length=10)),
                ('capacidad', models.CharField(choices=[('16GB', '16GB'), ('32GB', '32GB'), ('64GB', '64GB'), ('128GB', '128GB'), ('256GB', '256GB'), ('512GB', '512GB')], max_length=5)),
                ('imei', models.BigIntegerField()),
                ('imei2', models.BigIntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_venta', models.DateField(blank=True, null=True)),
                ('fecha_compra', models.DateField(default=datetime.date(2021, 8, 29))),
                ('proveedor', models.CharField(max_length=50)),
                ('cliente', models.CharField(blank=True, max_length=50, null=True)),
                ('monto_compra', models.FloatField()),
                ('monto_venta', models.FloatField(blank=True, null=True)),
                ('vendido', models.BooleanField(default=False)),
                ('devuelto', models.BooleanField(null=True)),
                ('reservado', models.BooleanField(null=True)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='principal.modelotelefono')),
            ],
            options={
                'verbose_name_plural': 'Teléfonos',
                'ordering': ['modelo'],
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date(2021, 8, 29))),
                ('hora', models.TimeField(default=datetime.datetime(2021, 8, 29, 22, 52, 43, 704647))),
                ('dinero', models.FloatField(blank=True)),
                ('monedero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='principal.monedero')),
                ('telefono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='principal.telefono')),
            ],
            options={
                'verbose_name_plural': 'Transacciones',
                'ordering': ['fecha'],
            },
        ),
        migrations.AddField(
            model_name='monedero',
            name='telefonos',
            field=models.ManyToManyField(through='principal.Transaccion', to='principal.Telefono'),
        ),
    ]
