# Generated by Django 3.1.7 on 2021-08-30 03:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefono',
            name='monederos',
            field=models.ManyToManyField(through='principal.Transaccion', to='principal.Monedero'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='hora',
            field=models.TimeField(default=datetime.datetime(2021, 8, 29, 22, 53, 56, 960494)),
        ),
    ]
