# Generated by Django 3.1.7 on 2021-08-30 05:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20210829_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefono',
            name='fecha_compra',
            field=models.DateField(default=datetime.date(2021, 8, 30)),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='dinero',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='fecha',
            field=models.DateField(default=datetime.date(2021, 8, 30)),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='hora',
            field=models.TimeField(default=datetime.time(0, 23, 35, 952564)),
        ),
    ]
