# Generated by Django 3.1.7 on 2021-08-31 04:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_auto_20210830_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia banco', 'Transferencia banco'), ('Tarjeta de crédito', 'Tarjeta de crédito')], default='Efectivo', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='hora',
            field=models.TimeField(default=datetime.time(23, 1, 21, 890862)),
        ),
    ]
