# Generated by Django 3.1.7 on 2021-08-31 04:26

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_auto_20210830_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefono',
            name='bateria',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='hora',
            field=models.TimeField(default=datetime.time(23, 26, 24, 372771)),
        ),
    ]
