# Generated by Django 3.1.7 on 2021-08-31 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_auto_20210831_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefono',
            name='entrega',
            field=models.CharField(choices=[('Entregado', 'Entregado'), ('Enviado', 'Enviado')], default='Entregado', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='hora',
            field=models.TimeField(default=datetime.time(13, 43, 12, 944667)),
        ),
    ]
