# Generated by Django 3.1.7 on 2021-09-03 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0011_auto_20210903_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefono',
            name='llego_audifonos',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='llego_cargador',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='sefue_audifonos',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='sefue_cargador',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='hora',
            field=models.TimeField(default=datetime.time(12, 21, 34, 690806)),
        ),
    ]
