# Generated by Django 3.1.7 on 2021-09-04 17:39

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0012_auto_20210903_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloDispositivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('marca', models.CharField(choices=[('Samsung', 'Samsung'), ('Apple', 'Apple'), ('Xiaomi', 'Xiaomi'), ('LG', 'LG')], default='Apple', max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Modelos de dispositivos',
                'ordering': ['marca', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='accesorio',
            name='fecha_compra',
            field=models.DateField(default=datetime.date(2021, 9, 4)),
        ),
        migrations.AddField(
            model_name='accesorio',
            name='fecha_venta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accesorio',
            name='monto_compra',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='accesorio',
            name='monto_venta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='fecha_compra',
            field=models.DateField(default=datetime.date(2021, 9, 4)),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='fecha',
            field=models.DateField(default=datetime.date(2021, 9, 4)),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='hora',
            field=models.TimeField(default=datetime.time(12, 39, 38, 554744)),
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidad', models.CharField(choices=[('Open box', 'Open box'), ('Sellado', 'Sellado')], default='Open box', max_length=10)),
                ('capacidad', models.CharField(choices=[('128GB', '128GB'), ('256GB', '256GB'), ('512GB', '512GB'), ('1TB', '1TB'), ('2TB', '2TB')], max_length=5)),
                ('pulgadas', models.FloatField(default=11, validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(20)])),
                ('imei', models.IntegerField(blank=True, null=True)),
                ('serial', models.CharField(blank=True, max_length=20, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_compra', models.DateField(default=datetime.date(2021, 9, 4))),
                ('fecha_venta', models.DateField(blank=True, null=True)),
                ('proveedor', models.CharField(max_length=50)),
                ('cliente', models.CharField(blank=True, max_length=50, null=True)),
                ('monto_compra', models.FloatField(null=True)),
                ('monto_venta', models.FloatField(blank=True, null=True)),
                ('vendido', models.BooleanField(default=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('entrega', models.CharField(blank=True, choices=[('Entregado', 'Entregado'), ('Envio servientrega', 'Envio servientrega'), ('Envio cooperativa', 'Envio cooperativa')], default='Entregado', max_length=20, null=True)),
                ('llego_cargador', models.BooleanField(default=False)),
                ('llego_audifonos', models.BooleanField(default=False)),
                ('sefue_cargador', models.BooleanField(default=False)),
                ('sefue_audifonos', models.BooleanField(default=False)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='principal.modelodispositivo')),
                ('monederos', models.ManyToManyField(through='principal.Transaccion', to='principal.Monedero')),
            ],
            options={
                'verbose_name_plural': 'Dispositivos',
                'ordering': ['modelo'],
            },
        ),
        migrations.AddField(
            model_name='monedero',
            name='dispositivos',
            field=models.ManyToManyField(through='principal.Transaccion', to='principal.Dispositivo'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='dispositivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='principal.dispositivo'),
        ),
    ]
