# Generated by Django 3.1.7 on 2021-09-06 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0013_auto_20210904_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefono',
            name='llego_cargador_rapido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telefono',
            name='precio_audifonos',
            field=models.DecimalField(blank=True, decimal_places=2, default=5, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='telefono',
            name='precio_cargador',
            field=models.DecimalField(blank=True, decimal_places=2, default=4.5, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='telefono',
            name='precio_cargador_rapido',
            field=models.DecimalField(blank=True, decimal_places=2, default=12, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='telefono',
            name='sefue_cargador_rapido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accesorio',
            name='fecha_compra',
            field=models.DateField(default=datetime.date(2021, 9, 6)),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='fecha_compra',
            field=models.DateField(default=datetime.date(2021, 9, 6)),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='fecha_compra',
            field=models.DateField(default=datetime.date(2021, 9, 6)),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='fecha',
            field=models.DateField(default=datetime.date(2021, 9, 6)),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='hora',
            field=models.TimeField(default=datetime.time(12, 17, 40, 386244)),
        ),
    ]
