# Generated by Django 3.1.7 on 2021-09-07 16:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0014_auto_20210906_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesorio',
            name='cliente',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accesorio',
            name='descripcion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='accesorio',
            name='entrega',
            field=models.CharField(blank=True, choices=[('Entregado', 'Entregado'), ('Envio servientrega', 'Envio servientrega'), ('Envio cooperativa', 'Envio cooperativa')], default='Entregado', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='accesorio',
            name='monederos',
            field=models.ManyToManyField(through='principal.Transaccion', to='principal.Monedero'),
        ),
        migrations.AddField(
            model_name='accesorio',
            name='proveedor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accesorio',
            name='tipo',
            field=models.CharField(choices=[('Samsung', 'Samsung'), ('Apple', 'Apple')], default='Cable', max_length=15),
        ),
        migrations.AddField(
            model_name='accesorio',
            name='vendido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monedero',
            name='accesorios',
            field=models.ManyToManyField(through='principal.Transaccion', to='principal.Accesorio'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='accesorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='principal.accesorio'),
        ),
        migrations.AlterField(
            model_name='accesorio',
            name='fecha_compra',
            field=models.DateField(default=datetime.date(2021, 9, 7)),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='fecha_compra',
            field=models.DateField(default=datetime.date(2021, 9, 7)),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='fecha_compra',
            field=models.DateField(default=datetime.date(2021, 9, 7)),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='fecha',
            field=models.DateField(default=datetime.date(2021, 9, 7)),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='hora',
            field=models.TimeField(default=datetime.time(11, 32, 55, 795677)),
        ),
    ]
