# Generated by Django 3.1.7 on 2021-09-07 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0017_auto_20210907_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesorio',
            options={'ordering': ['marca', 'tipo'], 'verbose_name_plural': 'Accesorios'},
        ),
        migrations.RemoveField(
            model_name='accesorio',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='hora',
            field=models.TimeField(default=datetime.time(11, 56, 59, 302242)),
        ),
    ]
