# Generated by Django 3.1.7 on 2021-09-07 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0018_auto_20210907_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivo',
            name='pulgadas',
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='tamanio',
            field=models.FloatField(default=11),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='capacidad',
            field=models.CharField(choices=[('8GB', '8GB'), ('16GB', '16GB'), ('32GB', '32GB'), ('64GB', '64GB'), ('128GB', '128GB'), ('256GB', '256GB'), ('512GB', '512GB'), ('1TB', '1TB'), ('2TB', '2TB')], max_length=5),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='hora',
            field=models.TimeField(default=datetime.time(12, 23, 35, 346386)),
        ),
    ]
