# Generated by Django 3.1.7 on 2021-09-07 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0019_auto_20210907_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesorio',
            name='fecha_compra',
            field=models.DateField(blank=True, default=datetime.date(2021, 9, 7), null=True),
        ),
        migrations.AlterField(
            model_name='accesorio',
            name='fecha_venta',
            field=models.DateField(default=datetime.date(2021, 9, 7)),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='hora',
            field=models.TimeField(default=datetime.time(13, 57, 26, 208635)),
        ),
    ]
