# Generated by Django 3.1.7 on 2021-09-07 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0020_auto_20210907_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesorio',
            name='conexion',
            field=models.CharField(choices=[('Lightning', 'Lightning'), ('Tipo C', 'Tipo C'), ('Micro USB', 'Micro USB'), ('Inalámbrica', 'Inalámbrica'), ('Normal', 'Normal'), ('Otra', 'Otra')], default='Lightning', max_length=15),
        ),
        migrations.AlterField(
            model_name='accesorio',
            name='fecha_compra',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='hora',
            field=models.TimeField(default=datetime.time(14, 20, 45, 576494)),
        ),
    ]
