# Generated by Django 3.1.7 on 2021-09-07 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0021_auto_20210907_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesorio',
            name='tipo',
            field=models.CharField(choices=[('Cargador', 'Cargador'), ('Cable', 'Cable'), ('Adaptador', 'Adaptador'), ('Audífonos', 'Audífonos'), ('Protector', 'Protector'), ('Mica', 'Mica'), ('Otro', 'Otro')], default='Cable', max_length=15),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='hora',
            field=models.TimeField(default=datetime.time(14, 24, 15, 335266)),
        ),
    ]
